[project]
name = "asteroids"
version = "1.1.3"
description = "The eternal classic implemented with pygame "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame==2.6.1",
    "Pillow>=10.0.0",
]
